services:
  postgres_2:
    image: postgres:15
    container_name: postgres_container_2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

volumes:
  postgres_data2: